/* -------------------------------------------------------------- * | The TSO Tr
ansmit data that is being received is covered under  | | the GPL Version 3 Licen
se.                                     | |
                           | | Welcome to SAVELAB - the ISPF Edit command to mak
e using       | | Edit Labels worthwhile as they are now persistent and
 | | thus usable.                                                   | |
                                                       | | The most current vers
ion of this package can be found at       | | https://github.com/lbdyck/savelab
 ** always the most current  | | https://www.lbdsoftware.com
                | | https://www.cbttape.org in file 313 (check the updates page)
.  | |                                                                | * ------
-------------------------------------------------------- */
